// Traditional Chinese (default, zh-Hant-HK)
export const ZH = {
  'brand': '領養一站通',
  'brandFull': '領養一站通 HK Adopt Hub',
  'tagline': '香港狗貓領養一站化平台',
  'nav.home': '主頁',
  'nav.browse': '搵毛孩',
  'nav.orgs': '領養機構',
  'nav.applications': '我的申請',
  'nav.profile': '我的檔案',
  'nav.settings': '設定',
  'nav.about': '關於我們',
  'listing.contactRescuer': '💬 聯絡送養人',

  'hero.badge': '聚合全港狗貓領養資訊 · 一鍵直達機構申請',
  'hero.title1': '全港待領養狗貓，',
  'hero.title2': '一站睇晒，直接申請',
  'hero.sub': '領養資訊四散喺十幾個機構網站？我哋幫你聚合晒：唔使逐個網站搵，睇中邊隻就一鍵直達機構官網申請。填一次領養者檔案，去到邊都唔使再逐欄填。',
  'hero.ctaBrowse': '立即搵毛孩',
  'hero.ctaOrgs': '領養機構一覽',
  'hero.ctaProfile': '建立領養者檔案',
  'hero.statOrgs': '真實機構已收錄',
  'hero.statCases': '真實待領養個案',
  'hero.statCasesNote': '持續更新中',
  'hero.statHkdr': '單計救狗之家，就有約500隻狗等緊家',

  'how.title': '點樣領養？三步搞掂',
  'how.sub': '唔使再喺每個領養網站重複搵同重複填',
  'how.s1t': '① 建立領養者檔案',
  'how.s1d': '填一次你嘅住屋類型、養寵經驗、家庭狀況，之後可以一鍵複製成申請摘要，貼去任何機構表格。',
  'how.s2t': '② 一站瀏覽真實個案',
  'how.s2d': '聚合各機構官網嘅待領養狗貓，每個個案都附返源頭連結，資料永遠以機構官網為準。',
  'how.s3t': '③ 直達機構網站申請',
  'how.s3d': '撳一下就直接跳去機構嘅領養頁或申請表，唔使再喺唔同網站之間兜轉。',

  'home.featured': '真實待領養個案',
  'home.featuredSub': '資料來自機構官網 · 撳入去直接申請',
  'home.viewAll': '查看全部個案',
  'home.channelsTitle': '快捷申請渠道',
  'home.channelsSub': '直接去各機構嘅狗／貓領養專頁',
  'home.dogCta': '領養狗狗',
  'home.catCta': '領養貓貓',
  'home.orgCtaTitle': '你係動物領養機構？',
  'home.orgCtaSub': '希望更多領養人搵到你嘅毛孩？我哋可以免費收錄你嘅領養專頁連結，並喺下一階段開放自助上架。歡迎聯絡我哋。',

  'browse.title': '搵毛孩',
  'browse.sub': '聚合各機構官網嘅真實待領養個案，撳入去即到機構申請頁',
  'browse.search': '搜尋名字…',
  'browse.all': '全部',
  'browse.dogs': '狗隻',
  'browse.cats': '貓隻',
  'filters.title': '篩選條件',
  'filters.org': '領養機構',
  'filters.any': '不限',
  'filters.gender': '性別',
  'filters.male': '♂ 男仔',
  'filters.female': '♀ 女仔',
  'filters.age': '年齡',
  'filters.size': '體型',
  'filters.breed': '品種',
  'filters.favOnly': '只睇收藏',
  'filters.sort': '排序',
  'sort.default': '建議排序',
  'sort.ageAsc': '年幼 → 年長',
  'sort.ageDesc': '年長 → 年幼',
  'sort.name': '名稱 A–Z',
  'filters.clear': '清除篩選',
  'pet.age.baby': '幼年 (1歲以下)',
  'pet.age.young': '少年 (1-2歲)',
  'pet.age.adult': '成年 (2-10歲)',
  'pet.age.senior': '年長 (10歲+)',
  'pet.size.small': '小型',
  'pet.size.medium': '中型',
  'pet.size.large': '大型',
  'results.count': '共 {n} 個真實個案',
  'results.none': '搵唔到合適嘅個案',
  'results.noneHint': '試下放寬篩選，或者直接去「領養機構」睇晒所有機構專頁——毛孩天天新增！',
  'channels.goDogs': '🐶 狗隻領養頁',
  'channels.goCats': '🐱 貓隻領養頁',
  'channels.goAdoption': '🏠 領養專頁',
  'channels.applyForm': '📝 申請表',

  'listing.apply': '查看及申請',
  'listing.source': '來源',
  'listing.record': '記錄申請',
  'listing.recorded': '已記錄',
  'listing.snapshot': '資料快照：2026-08-28。個案隨時被領養，狀況以機構官網為準。',
  'listing.fav': '收藏',
  'listing.faved': '已收藏',
  'listing.share': '分享',
  'listing.shareCopied': '已複製連結',
  'listing.loadMore': '載入更多毛孩',
  'listing.photoNote': '相片即時連結自機構官網，版權屬各機構所有。',

  'orgs.title': '領養機構',
  'orgs.sub': '全部真實機構，連結直達官方領養頁',
  'orgs.sourceNote': '✅ 以下全部為真實機構（2026-08-28 核實連結）。本站只做聚合同轉介，領養程序一律以機構為準。',
  'orgs.visit': '🔗 官方網站',
  'orgs.moreTitle': '更多領養渠道',
  'orgs.moreSub': '以下組織暫時未能自動收錄個案（網站有Bot驗證、以社交平台發布、或以貓狗以外動物為主），但一樣有毛孩等緊一個家，一按直達：',
  'orgs.districts': '地區',
  'orgs.contact': '聯絡',
  'orgs.allHK': '全港',
  'orgs.listedCount': '🏡 已收錄 {n} 個真實個案',

  'profile.title': '我的領養者檔案',
  'profile.sub': '填一次，去到邊個機構都使得。申請時一鍵複製摘要。',
  'profile.create': '建立檔案',
  'profile.update': '更新檔案',
  'profile.saved': '已儲存檔案 ✓',
  'profile.updated': '檔案已更新 ✓',
  'profile.name': '稱呼',
  'profile.namePh': '例如：陳大文',
  'profile.phone': '聯絡電話',
  'profile.phonePh': '例如：9123 4567',
  'profile.email': '電郵',
  'profile.housing': '住屋類型',
  'housing.private': '私人樓宇',
  'housing.hos': '居屋',
  'housing.public': '公共屋邨',
  'housing.village': '村屋',
  'housing.house': '洋房／獨立屋',
  'profile.hasKids': '家中有小朋友（12歲以下）',
  'profile.hasPets': '家中現有寵物',
  'profile.experience': '養寵物經驗',
  'exp.none': '新手',
  'exp.some': '有經驗',
  'exp.expert': '資深（曾養多隻／長期）',
  'profile.dailyHours': '每日可以陪毛孩活動時間',
  'profile.hoursUnit': '小時',
  'profile.intro': '自我介紹（俾機構更加了解你）',
  'profile.introPh': '例如：一家三口住村屋，有花園，想領養一隻親人嘅狗陪阿嫲散步…',
  'profile.required': '此欄必填',
  'profile.badEmail': '請輸入有效電郵',
  'profile.haveOne': '你已經有檔案，申請任何機構時都可以一鍵複製摘要。',
  'profile.seeApps': '查看我的申請',
  'profile.copy': '📋 複製我的申請摘要',
  'profile.copied': '已複製申請摘要！去機構網站貼上就得 ✓',
  'profile.copyHint': '呢份摘要按照標準領養申請格式生成，可以貼去任何機構嘅表格或電郵。',

  'apps.title': '我的申請',
  'apps.sub': '自行記錄申請進度，唔使再靠記性',
  'apps.none': '仲未有任何記錄',
  'apps.noneHint': '喺毛孩卡片撳「記錄申請」，追蹤你喺唔同機構嘅申請進度！',
  'apps.noneCta': '去搵毛孩',
  'apps.submittedAt': '記錄於',
  'apps.updatedAt': '最後更新',
  'apps.advance': '更新狀態',
  'apps.remove': '刪除記錄',
  'apps.removeConfirm': '確定刪除呢個記錄？',
  'apps.manualNote': '呢頁係你嘅私人追蹤清單：喺機構網站遞交申請之後，喺度自行更新狀態。',
  'apps.viewSource': '前往機構頁面 ↗',
  'status.submitted': '已遞交',
  'status.reviewing': '機構審核中',
  'status.interview': '安排會面',
  'status.approved': '領養成功 🎉',
  'status.rejected': '未能成事',

  'settings.title': '設定',
  'settings.lang': '顯示語言',
  'settings.langHint': '預設為繁體中文（香港）。選擇後即時切換全站文字。',
  'lang.zh': '繁體中文',
  'lang.en': 'English',
  'settings.data': '我的資料',
  'settings.dataHint': '所有資料（檔案、申請記錄、收藏）只儲存喺你嘅瀏覽器，唔會上傳，亦唔需要帳戶。',
  'settings.reset': '清除所有本地資料',
  'settings.resetConfirm': '確定清除所有檔案、申請記錄同收藏？此操作無法復原。',
  'settings.resetDone': '已清除所有本地資料',
  'settings.note': '關於此平台',
  'settings.noteBody': '領養一站通聚合各機構公開嘅領養資訊並附來源連結，本身唔代表任何機構，領養申請一律喺機構官網進行。',

  'about.title': '關於領養一站通',
  'about.whyTitle': '點解要做呢個平台？',
  'about.whyBody': '香港有好多有心人想做領養人，但領養資訊散落喺十幾個唔同網站同社交媒體：要逐個網站搵、逐個註冊、逐個填長表，好多人搵搵下就放棄——毛孩就少咗機會遇到家。領養一站通將啲資訊聚合埋一齊，每個個案直達機構官網，令「搵到、申請到」變得簡單。',
  'about.m1t': '一站式整合',
  'about.m1d': '聚合全港狗貓領養資訊，一個平台睇晒所有選擇。',
  'about.m2t': '直達機構申請',
  'about.m2d': '每個個案同機構都附官方連結，一鍵跳去申請，唔經第三方。',
  'about.m3t': '提高領養率',
  'about.m3d': '降低搵嘅成本、簡化申請流程，最終目標係俾更多毛孩有一個家。',
  'about.p1d': '狗隻及貓隻領養資訊聚合、真實個案直達連結、領養者檔案、申請追蹤、繁中／英文介面。',
  'about.p2d': '同機構合作自動同步個案（官方 API／資料提供），開放機構自助上架，加埋其他動物種類。',
  'about.p3d': '領養後支援：新丁指南、獸醫網絡、義工運送網絡。',
  'about.contactTitle': '聯絡我哋',
  'about.contactBody': '機構收錄／合作／任何建議：info@hkadopt.com',
  'about.sourcesTitle': '資料來源',
  'about.sourcesSub': '本站全部個案同機構資訊嚟自以下官方網站（快照：{date}，每日自動更新）：',
  'about.disclaimer': '免責聲明：本站為獨立聚合平台，同列表內機構唔隸屬亦唔代表任何機構。個案資訊嚟自機構公開網頁，版權屬於各機構；領養前請務必以機構官網最新資料為準。',

  'footer.blurb': '香港狗貓領養一站化平台。聚合真實個案，直達機構申請，俾更多毛孩搵到屋企。',
  'footer.links': '網站地圖',
  'footer.phase2': '下一階段：機構自助上架 · 個案自動同步',
  'footer.rights': '© 2026 領養一站通 HK Adopt Hub · 個案版權屬各機構所有',
  'common.backHome': '返回主頁',
  'common.back': '返回',
} as const;

export type DictKey = keyof typeof ZH;
