import type { DictKey } from './dict';

// English — mirrors every key in ZH
export const EN: Record<DictKey, string> = {
  'brand': 'HK Adopt Hub',
  'brandFull': 'HK Adopt Hub 領養一站通',
  'tagline': "Hong Kong's one-stop dog & cat adoption directory",
  'nav.home': 'Home',
  'nav.browse': 'Find a Pet',
  'nav.orgs': 'Adoption Orgs',
  'nav.applications': 'My Applications',
  'nav.profile': 'My Profile',
  'nav.settings': 'Settings',
  'nav.about': 'About',
  'listing.contactRescuer': '💬 Contact rescuer',

  'hero.badge': 'All HK dog & cat adoptions in one place · apply directly on each org’s site',
  'hero.title1': 'Every adoptable dog & cat in HK,',
  'hero.title2': 'one hub, straight to the source',
  'hero.sub': 'Adoption listings are scattered across a dozen organisation websites. We bring them together — and every case links straight to the organisation’s own page to apply. Fill your adopter profile once, then reuse it everywhere.',
  'hero.ctaBrowse': 'Find a Pet',
  'hero.ctaOrgs': 'Browse Organisations',
  'hero.ctaProfile': 'Create Adopter Profile',
  'hero.statOrgs': 'Real organisations listed',
  'hero.statCases': 'Real adoption cases',
  'hero.statCasesNote': 'continuously updated',
  'hero.statHkdr': 'HKDR alone has ~500 dogs waiting for homes',

  'how.title': 'Adopting is easy — 3 steps',
  'how.sub': 'No more searching — and re-filling forms — on every adoption website',
  'how.s1t': '① Create your adopter profile',
  'how.s1d': 'Fill in your housing, experience and household once, then copy it as a ready-made application summary for any organisation’s form.',
  'how.s2t': '② Browse real cases in one place',
  'how.s2d': 'We aggregate adoptable dogs and cats from orgs’ own websites — every case links back to its source, so the org’s page is always the truth.',
  'how.s3t': '③ Apply on the org’s site',
  'how.s3d': 'One tap takes you straight to the organisation’s adoption page or application form — no more bouncing between sites.',

  'home.featured': 'Real adoption cases',
  'home.featuredSub': 'From organisations’ own sites · tap to apply at source',
  'home.viewAll': 'View all cases',
  'home.channelsTitle': 'Quick application channels',
  'home.channelsSub': 'Jump straight to each org’s dog / cat adoption pages',
  'home.dogCta': 'Adopt a dog',
  'home.catCta': 'Adopt a cat',
  'home.orgCtaTitle': 'Are you an animal adoption organisation?',
  'home.orgCtaSub': 'Want more adopters to find your animals? We’ll list your adoption page links for free, with self-service listings coming in the next phase. Get in touch.',

  'browse.title': 'Find a Pet',
  'browse.sub': 'Real cases aggregated from organisations’ own sites — tap through to apply',
  'browse.search': 'Search name…',
  'browse.all': 'All',
  'browse.dogs': 'Dogs',
  'browse.cats': 'Cats',
  'filters.title': 'Filters',
  'filters.org': 'Organisation',
  'filters.any': 'Any',
  'filters.gender': 'Gender',
  'filters.male': '♂ Male',
  'filters.female': '♀ Female',
  'filters.age': 'Age',
  'filters.size': 'Size',
  'filters.breed': 'Breed',
  'filters.favOnly': 'Favourites only',
  'filters.sort': 'Sort',
  'sort.default': 'Recommended',
  'sort.ageAsc': 'Youngest first',
  'sort.ageDesc': 'Oldest first',
  'sort.name': 'Name A–Z',
  'filters.clear': 'Clear filters',
  'pet.age.baby': 'Baby (<1yr)',
  'pet.age.young': 'Young (1–2yrs)',
  'pet.age.adult': 'Adult (2–10yrs)',
  'pet.age.senior': 'Senior (10yrs+)',
  'pet.size.small': 'Small',
  'pet.size.medium': 'Medium',
  'pet.size.large': 'Large',
  'results.count': '{n} real cases',
  'results.none': 'No cases match your filters',
  'results.noneHint': 'Try widening the filters, or visit “Adoption Orgs” for every organisation’s page — new pets arrive every day!',
  'channels.goDogs': '🐶 Dog adoption page',
  'channels.goCats': '🐱 Cat adoption page',
  'channels.goAdoption': '🏠 Adoption page',
  'channels.applyForm': '📝 Application form',

  'listing.apply': 'View & apply',
  'listing.source': 'Source',
  'listing.record': 'Track application',
  'listing.recorded': 'Tracking',
  'listing.snapshot': 'Snapshot: 2026-08-28. Cases get adopted fast — status is always authoritative on the organisation’s own site.',
  'listing.fav': 'Favourite',
  'listing.faved': 'Favourited',
  'listing.share': 'Share',
  'listing.shareCopied': 'Link copied',
  'listing.loadMore': 'Load more pets',
  'listing.photoNote': 'Photos are hotlinked live from the organisations’ own sites and remain their copyright.',

  'orgs.title': 'Adoption Organisations',
  'orgs.sub': 'All real organisations, linked directly to their official adoption pages',
  'orgs.sourceNote': '✅ Every organisation below is real (links verified 2026-08-28). We only aggregate and refer — adoption procedures are defined by each organisation.',
  'orgs.visit': '🔗 Official website',
  'orgs.moreTitle': 'More adoption channels',
  'orgs.moreSub': 'These rescues can’t be auto-indexed yet (bot-protected sites, social-media-only listings, or non-cat/dog focus) — but their animals are just as deserving. One tap away:',
  'orgs.districts': 'Areas',
  'orgs.contact': 'Contact',
  'orgs.allHK': 'Territory-wide',
  'orgs.listedCount': '🏡 {n} real cases indexed',

  'profile.title': 'My Adopter Profile',
  'profile.sub': 'Fill once, use at every organisation. Copy your summary when applying.',
  'profile.create': 'Create profile',
  'profile.update': 'Update profile',
  'profile.saved': 'Profile saved ✓',
  'profile.updated': 'Profile updated ✓',
  'profile.name': 'Name',
  'profile.namePh': 'e.g. Chan Tai Man',
  'profile.phone': 'Phone',
  'profile.phonePh': 'e.g. 9123 4567',
  'profile.email': 'Email',
  'profile.housing': 'Housing type',
  'housing.private': 'Private flat',
  'housing.hos': 'HOS flat',
  'housing.public': 'Public housing',
  'housing.village': 'Village house',
  'housing.house': 'Detached house',
  'profile.hasKids': 'Children at home (under 12)',
  'profile.hasPets': 'Pets at home already',
  'profile.experience': 'Pet ownership experience',
  'exp.none': 'First-timer',
  'exp.some': 'Experienced',
  'exp.expert': 'Veteran (multiple / long-term)',
  'profile.dailyHours': 'Daily time for the pet',
  'profile.hoursUnit': 'hours',
  'profile.intro': 'About you (helps orgs get to know you)',
  'profile.introPh': 'e.g. Family of three in a village house with a garden, hoping to adopt a friendly dog to keep grandma company on walks…',
  'profile.required': 'This field is required',
  'profile.badEmail': 'Please enter a valid email',
  'profile.haveOne': 'You already have a profile — copy your summary any time you apply.',
  'profile.seeApps': 'View my applications',
  'profile.copy': '📋 Copy my application summary',
  'profile.copied': 'Summary copied! Just paste it into the organisation’s form ✓',
  'profile.copyHint': 'Generated in a standard adoption-application format — paste it into any org’s form or email.',

  'apps.title': 'My Applications',
  'apps.sub': 'Track your application progress yourself — no more relying on memory',
  'apps.none': 'Nothing tracked yet',
  'apps.noneHint': 'Hit “Track application” on any pet card to follow your progress across organisations!',
  'apps.noneCta': 'Find a pet',
  'apps.submittedAt': 'Recorded',
  'apps.updatedAt': 'Last update',
  'apps.advance': 'Update status',
  'apps.remove': 'Delete record',
  'apps.removeConfirm': 'Delete this record?',
  'apps.manualNote': 'This is your private tracking list: after you submit an application on an organisation’s site, update the status here.',
  'apps.viewSource': 'Open org page ↗',
  'status.submitted': 'Submitted',
  'status.reviewing': 'Under review',
  'status.interview': 'Meet & greet',
  'status.approved': 'Adopted 🎉',
  'status.rejected': 'Unsuccessful',

  'settings.title': 'Settings',
  'settings.lang': 'Display language',
  'settings.langHint': 'Traditional Chinese (Hong Kong) is the default. Changes apply instantly.',
  'lang.zh': '繁體中文',
  'lang.en': 'English',
  'settings.data': 'My data',
  'settings.dataHint': 'Everything (profile, tracked applications, favourites) is stored only in your browser — no uploads, no accounts.',
  'settings.reset': 'Clear all local data',
  'settings.resetConfirm': 'Clear all profiles, tracked applications and favourites? This cannot be undone.',
  'settings.resetDone': 'All local data cleared',
  'settings.note': 'About this platform',
  'settings.noteBody': 'HK Adopt Hub aggregates publicly available adoption info and links to its sources. We are not affiliated with any organisation — all applications happen on the organisations’ own websites.',

  'about.title': 'About HK Adopt Hub',
  'about.whyTitle': 'Why build this?',
  'about.whyBody': 'Hong Kong has many people who want to adopt, but the listings are scattered across a dozen websites and social pages. You have to hunt site by site, register again and again, and fill the same long forms — many give up halfway, and pets lose their chance to find a home. HK Adopt Hub pulls the listings together, with every case linking straight to the organisation, so “found it, applied for it” becomes one simple flow.',
  'about.m1t': 'One-stop aggregation',
  'about.m1d': 'Bring together dog & cat adoption listings across Hong Kong — see every option on one platform.',
  'about.m2t': 'Apply at the source',
  'about.m2d': 'Every case and organisation links to its official page — one tap to apply, no middleman.',
  'about.m3t': 'Higher adoption rates',
  'about.m3d': 'Cut the cost of searching, simplify applying — the end goal is more pets finding a home.',
  'about.p1d': 'Dog & cat listing aggregation, direct source links, adopter profiles, application tracking, zh-Hant/English UI.',
  'about.p2d': 'Automatic case sync with organisations (official APIs / data feeds), self-service listings, more species.',
  'about.p3d': 'Post-adoption support: starter guides, vet network, volunteer transport network.',
  'about.contactTitle': 'Contact us',
  'about.contactBody': 'Listing requests / partnerships / feedback: info@hkadopt.com',
  'about.sourcesTitle': 'Sources',
  'about.sourcesSub': 'All cases and organisation info come from these official websites (snapshot: {date}, auto-updated daily):',
  'about.disclaimer': 'Disclaimer: this is an independent aggregation platform, not affiliated with nor representing any organisation listed. Case information comes from organisations’ public web pages and remains their copyright. Always confirm details on the organisation’s official site before adopting.',

  'footer.blurb': "Hong Kong's one-stop dog & cat adoption directory. Real cases, straight to the source, more pets homed.",
  'footer.links': 'Site map',
  'footer.phase2': 'Coming next: self-service org listings · automatic case sync',
  'footer.rights': '© 2026 HK Adopt Hub 領養一站通 · Case content remains the copyright of each organisation',
  'common.backHome': 'Back to home',
  'common.back': 'Back',
};
